//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf6
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int ID_customer { get; set; }
        public string firstname { get; set; }
        public string surname { get; set; }
        public string middlename { get; set; }
        public int ID_seasonticket { get; set; }
        public int ID_trainer { get; set; }
    
        public virtual seasonticket seasonticket { private get; set; }
        public virtual trainer trainer { private get; set; }
    }
}
